name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows GitHub Actions to create and upload releases

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Define the platforms you want to support

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tictactoe/requirements.txt  # Adjust the path if necessary

    - name: Build Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.9'
        spec: 'tictactoe/main.spec'
        requirements: 'tictactoe/requirements.txt'
        upload_exe_with_name: ${{ matrix.os }}-tictactoe
        options: --onefile --windowed --icon=assets/icon.ico --add-data "tictactoe/assets/icon.png;assets" --add-data "tictactoe/assets/icon.ico;assets"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/release/${{ matrix.os }}-tictactoe${{ (matrix.os == 'windows-latest') && '.exe' || '' }}
        asset_name: tictactoe${{ (matrix.os == 'windows-latest') && '.exe' || '' }}
        asset_content_type: ${{ (matrix.os == 'windows-latest') && 'application/x-msdownload' || 'application/x-executable' }}
