name: Run and Test

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  python-run-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Adjust the path if necessary

      - name: Run Files
        run: |
          Start-Process python -ArgumentList "main.py" -NoNewWindow -PassThru | Out-Null
          Start-Sleep -Seconds 10
        # run: python main.py || echo "Script exited with errors" # Run script and capture errors

      - name: Test
        run: pytest
